name: fquery
description: Simple yet powerful async state management solution with in-built caching
version: 3.0.1
repository: https://github.com/41y08h/fquery

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed: ^3.0.5
  freezed_annotation: ^3.0.0
  fquery_core:
    path: ../fquery_core

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.16.0
