name: fquery_core
description: Core library used by fquery
version: 3.0.2
repository: https://github.com/41y08h/fquery
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  freezed: ^3.0.5
  freezed_annotation: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.9
  lints: ^5.0.0
  test: ^1.24.0
