name: Publish to pub.dev

on:
  push:
    tags:
      - 'fquery-v[0-9]+.[0-9]+.[0-9]+*'
      - 'fquery_core-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_fquery:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
     working-directory: packages/fquery
     
  publish_fquery_core:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
     working-directory: packages/fquery_core
